language: go
go_import_path: github.com/heptiolabs/certstream-slack
go:
  - 1.9.x

sudo: false

install:
  - go get -u github.com/golang/dep/cmd/dep
    && dep ensure -vendor-only -v

script:
  - go install -v ./... && go test ./...
